import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, fonts, spacing, borderRadius } from '../theme';

function Section({ title, children }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

export default function TermsOfServiceScreen({ navigation }) {
  const insets = useSafeAreaInsets();

  return (
    <View style={[styles.root, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <MaterialCommunityIcons name="arrow-left" size={22} color={colors.text} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={{ width: 38 }} />
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.content}
      >
        <Text style={styles.lastUpdated}>Last updated: May 2026</Text>

        <Text style={styles.intro}>
          By downloading or using CoinSeek, you agree to these Terms of Service.
          Please read them carefully before using the app.
        </Text>

        <Section title="1. Acceptance of Terms">
          {`By accessing or using CoinSeek, you confirm that you are at least 13 years old and agree to be bound by these Terms of Service. If you do not agree, please do not use CoinSeek.`}
        </Section>

        <Section title="2. Description of Service">
          {`CoinSeek is a mobile application that uses artificial intelligence to identify coins, estimate their value, and help users manage their coin collections. Coin identifications and valuations are provided as estimates only and should not be relied upon for financial or investment decisions.`}
        </Section>

        <Section title="3. User Accounts">
          {`You are responsible for:\n\n• Maintaining the confidentiality of your account credentials\n• All activity that occurs under your account\n• Providing accurate information when creating your account\n• Notifying us immediately of any unauthorised use of your account\n\nWe reserve the right to suspend or terminate accounts that violate these terms.`}
        </Section>

        <Section title="4. Free Trial">
          {`New users receive a 7-day free trial with access to limited features (up to 3 coin scans per day). At the end of the trial period, a Premium subscription is required to continue using paid features. No credit card is required to start the free trial.`}
        </Section>

        <Section title="5. Subscriptions & Billing">
          {`CoinSeek offers the following subscription plans:\n\n• Monthly — €1.99 per month\n• Annual — €18.99 per year\n\nSubscriptions automatically renew at the end of each billing period unless cancelled. You can cancel at any time through the app. Cancellation takes effect at the end of the current billing period — you will retain access until then.\n\nAll payments are processed securely by Stripe. Prices may be subject to local taxes.`}
        </Section>

        <Section title="6. Refund Policy">
          {`We offer a 30-day money-back guarantee on all new subscriptions. If you are not satisfied with CoinSeek Premium within 30 days of your first payment, contact us at support@coinseek.app for a full refund.\n\nRefunds are not available for subsequent billing periods or if your account has been terminated for violating these terms.`}
        </Section>

        <Section title="7. Acceptable Use">
          {`You agree not to:\n\n• Use CoinSeek for any unlawful purpose\n• Attempt to reverse engineer or copy the app\n• Use automated tools to scrape or abuse the service\n• Share your account with others\n• Attempt to circumvent scan limits or payment requirements\n• Upload inappropriate or illegal content`}
        </Section>

        <Section title="8. AI Identification Disclaimer">
          {`Coin identifications and valuations provided by CoinSeek are generated by artificial intelligence and are estimates only. They may not be accurate and should not be used as the sole basis for buying, selling, or insuring coins. Always consult a professional numismatist for high-value coins.`}
        </Section>

        <Section title="9. Intellectual Property">
          {`All content, features, and functionality of CoinSeek — including the design, code, and coin database — are owned by CoinSeek and protected by copyright and intellectual property laws. You may not copy, modify, or distribute any part of the app without our written permission.`}
        </Section>

        <Section title="10. Limitation of Liability">
          {`To the fullest extent permitted by law, CoinSeek shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app. Our total liability for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.`}
        </Section>

        <Section title="11. Changes to Terms">
          {`We may update these Terms of Service at any time. We will notify you of significant changes via email or in-app notification. Continued use of CoinSeek after changes are posted means you accept the updated terms.`}
        </Section>

        <Section title="12. Governing Law">
          {`These terms are governed by the laws of Ireland. Any disputes shall be subject to the exclusive jurisdiction of the courts of Ireland.`}
        </Section>

        <Section title="13. Contact Us">
          {`If you have any questions about these Terms of Service, please contact us at:\n\nsupport@coinseek.app`}
        </Section>

        <View style={{ height: 48 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },

  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: spacing.md, paddingVertical: spacing.md,
    borderBottomWidth: 1, borderBottomColor: colors.outlineVariant,
  },
  backBtn: {
    width: 38, height: 38, borderRadius: 19,
    backgroundColor: colors.surfaceContainer,
    alignItems: 'center', justifyContent: 'center',
  },
  headerTitle: { fontFamily: fonts.sansBold, fontSize: 17, color: colors.text },

  content: { paddingHorizontal: spacing.edge, paddingTop: spacing.lg },

  lastUpdated: {
    fontFamily: fonts.sans, fontSize: 12, color: colors.textMuted,
    marginBottom: spacing.md,
  },
  intro: {
    fontFamily: fonts.sans, fontSize: 14, color: colors.textMuted,
    lineHeight: 22, marginBottom: spacing.lg,
  },

  section: { marginBottom: spacing.lg },
  sectionTitle: {
    fontFamily: fonts.sansBold, fontSize: 15, color: colors.primary,
    marginBottom: spacing.sm,
  },
  sectionBody: {
    fontFamily: fonts.sans, fontSize: 14, color: colors.textMuted,
    lineHeight: 22,
  },
});
