import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Coin Seek',
  description: 'Terms and conditions for using the Coin Seek waitlist and application.',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0d0d0d] text-white">
      <header className="border-b border-[rgba(255,184,0,0.08)] px-8 py-4">
        <div className="max-w-2xl mx-auto flex justify-between items-center">
          <Link href="/" className="font-mono text-[#FFB800] text-sm tracking-[3px] hover:opacity-80 transition-opacity">
            COIN//SEEK
          </Link>
          <Link href="/" className="font-mono text-[11px] text-[#888] tracking-[2px] hover:text-[#FFB800] transition-colors">
            ← BACK
          </Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-8 py-16">
        <p className="font-mono text-[11px] text-[#FFB800] tracking-[3px] mb-4">// LEGAL</p>
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="font-mono text-[11px] text-[#555] tracking-[2px] mb-12">
          LAST UPDATED: JUNE 2026
        </p>

        <div className="space-y-10 text-[#aaa] leading-relaxed text-sm">

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">1. ACCEPTANCE</h2>
            <p>
              By accessing this website or joining the Coin Seek waitlist, you agree to be bound by these
              Terms of Service. If you do not agree, do not use the service.
            </p>
            <p className="mt-3">
              These terms apply to the pre-launch waitlist and, once available, the Coin Seek mobile
              application ("the App"). Questions? Email{' '}
              <a href="mailto:swiftsitesireland@gmail.com" className="text-[#FFB800] hover:underline">
                swiftsitesireland@gmail.com
              </a>
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">2. THE SERVICE</h2>
            <p>
              Coin Seek is an AI-powered mobile application that helps users identify coins, estimate
              rarity, and obtain indicative market values. The service is currently in pre-launch; joining the
              waitlist does not guarantee access, a specific launch date, or any particular features.
            </p>
            <p className="mt-3">
              We reserve the right to modify, pause, or discontinue any part of the service at any time without
              prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">3. WAITLIST</h2>
            <ul className="space-y-2 list-none">
              {[
                'You must provide a valid email address to join the waitlist.',
                'One entry per person. Duplicate entries for the same email are silently merged.',
                'Joining the waitlist does not create a user account or any contractual obligation on our part.',
                'We may remove entries that appear to be spam or automated submissions.',
              ].map((item) => (
                <li key={item} className="flex gap-3">
                  <span className="text-[#FFB800] font-mono shrink-0">→</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">4. COIN VALUATIONS — IMPORTANT DISCLAIMER</h2>
            <p>
              Any coin identification results, rarity scores, or market value estimates provided by the App are
              generated by AI and are for <strong className="text-white">informational and entertainment purposes only</strong>.
              They do not constitute financial advice, a professional appraisal, or an offer to buy or sell.
            </p>
            <p className="mt-3">
              Coin values fluctuate. Always consult a certified numismatist or dealer before making purchasing,
              selling, or insurance decisions based on a coin's value. We accept no liability for losses arising
              from reliance on AI-generated valuations.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">5. ACCEPTABLE USE</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="space-y-2 list-none">
              {[
                'Submit false, misleading, or fraudulent information.',
                'Attempt to scrape, reverse-engineer, or attack the service.',
                'Use automated tools to join the waitlist multiple times.',
                'Use the service in any way that violates applicable laws or regulations.',
                'Attempt to circumvent rate limits or security controls.',
              ].map((item) => (
                <li key={item} className="flex gap-3">
                  <span className="text-[#FFB800] font-mono shrink-0">→</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">6. INTELLECTUAL PROPERTY</h2>
            <p>
              All content on this website — including text, graphics, logos, and software — is owned by or
              licensed to Coin Seek and is protected by applicable intellectual property laws. You may not
              reproduce, distribute, or create derivative works without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">7. LIMITATION OF LIABILITY</h2>
            <p>
              To the maximum extent permitted by law, Coin Seek and its operators shall not be liable for
              any indirect, incidental, special, consequential, or punitive damages arising from your use of
              (or inability to use) the service.
            </p>
            <p className="mt-3">
              Our total aggregate liability for any claim related to the service shall not exceed the amount
              you paid us in the 12 months preceding the claim (or £50, whichever is greater).
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">8. DISCLAIMER OF WARRANTIES</h2>
            <p>
              The service is provided <strong className="text-white">"as is"</strong> and{' '}
              <strong className="text-white">"as available"</strong> without warranties of any kind, express or
              implied, including but not limited to merchantability, fitness for a particular purpose, or
              non-infringement. We do not warrant that the service will be uninterrupted, error-free, or that
              AI identifications will be accurate.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">9. PRIVACY</h2>
            <p>
              Your use of the service is also governed by our{' '}
              <Link href="/privacy" className="text-[#FFB800] hover:underline">
                Privacy Policy
              </Link>
              , which is incorporated into these terms by reference.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">10. CHANGES TO TERMS</h2>
            <p>
              We may update these terms at any time. We will notify waitlist subscribers of material changes by
              email. Continued use of the service after changes take effect constitutes your acceptance of the
              revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-base mb-3 font-mono tracking-wider">11. GOVERNING LAW</h2>
            <p>
              These terms are governed by and construed in accordance with applicable law. Any disputes arising
              under these terms shall be subject to the exclusive jurisdiction of the courts in the territory
              where the operator is based.
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-[rgba(255,184,0,0.08)] px-8 py-4 mt-8">
        <div className="max-w-2xl mx-auto flex justify-between items-center">
          <span className="font-mono text-[#2a2a2a] text-[10px] tracking-[2px]">COIN//SEEK</span>
          <div className="flex gap-6">
            <Link href="/privacy" className="font-mono text-[9px] text-[#555] hover:text-[#FFB800] tracking-[1px] transition-colors">PRIVACY</Link>
            <Link href="/terms" className="font-mono text-[9px] text-[#FFB800] tracking-[1px]">TERMS</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
